name: Publish AuroraSDK on NuGet

on:
  push:
    branches: [main]
    paths: ["*/**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore Aurora.Sdk.sln
      
      - name: Create directory
        run: mkdir publish

      - name: Build
        run: dotnet build --no-restore Aurora.Sdk.sln

      - name: Package Api
        run: dotnet build -c Debug -o publish/ Aurora.Api/Aurora.Api.csproj

      - name: Package entities
        run: dotnet build -c Debug -o publish/ Aurora.Api.Entities/Aurora.Api.Entities.csproj
     
      - name: Package turbine
        run: dotnet build -c Debug -o publish/ Aurora.Turbine.Api/Aurora.Turbine.Api.csproj
      
      - name: Package RabbitMQ
        run: dotnet build -c Debug -o publish/ Aurora.RabbitMq/Aurora.RabbitMq.csproj

      - name: Publish on NuGet
        run: dotnet nuget push publish/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
